services:
  db:
    image: postgres:15-alpine
    container_name: letshare-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql:ro